---
apiVersion: v1
kind: Pod
metadata:
  name: mikey-pod
  labels:
    app: nginx
spec:
  initContainers: 
    - image: alpine
      command:
        - sleep
        - 30s
  containers:
    - image: alpine
      name: mikey-cont
      command:
        - sleep
        - "10s"   
  restartPolicy: Always

