---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jenkins
spec:
  containers:
    - name: mikey-cont
      image: jenkins/jenkins
      ports:
        - containerPort: 8080
          protocol: TCP