apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mikey-rs
  labels:
    app: nginx
spec:
  minReadySeconds: 3
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: mikey-pod
      labels:
        app: nginx
    spec:
      containers:
        - name: mikey-cont
          image: nginx
          ports:
            - containerPort: 80
              protocol: TCP
      