apiVersion: v1
kind: ReplicationController
metadata:
  name: mikey-rc
  labels:
    app: jenkins
spec:
  minReadySeconds: 20
  replicas: 5
  selector: 
    app: jenkins
  template:
    metadata:
      name: mikey-pod1
      labels:
        app: jenkins
    spec:
      containers:
        - name: mikey-jenkinscont
          image: jenkins/jenkins
          ports:
            - containerPort: 8080
              protocol: TCP
  