apiVersion: v1
kind: ReplicationController
metadata:
  name: mikey-rc
  labels:
    app: jenkins
spec:
  minReadySeconds: 3
  replicas: 4
  selector: 
    app: jenkins
  template:
    metadata:
      name: mikey-pod1
      labels:
        app: jenkins
    spec:
      containers:
        - name: mikey-jenkinscont
          image: jenkins/jenkins
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mikey-svc1
  labels:
    app: mikey
spec:
  ports:
    - targetPort: 8080
      port: 35000
  selector:
    app: jenkins
  type: NodePort
      
  